var canvas = document.getElementById("screen");
canvas.height = window.innerHeight;
canvas.width = window.innerWidth;
var ctx = canvas.getContext('2d');

var obstacles_above=[];
var obstacles_below=[];
var widths=[20,30,25,20,30,25,45,15,65,45];
var heights=[35,35,40,30,40,40,20,55,10,45];
var ch=window.innerHeight;
var cw=window.innerWidth;
var y_coordinates=[ch-35,ch-35,ch-40,ch-30,ch-40,ch-40,ch-20,ch-55,ch-10,ch-45];
var radius = 10;
var player;
var player1;
var j;
var score=0;
var setAnimation;
var GAME_OVER = 0;
var s=0;
var a1=0,a2=0;
var wallspace = window.innerWidth/8;
var l;
var lives = [], life, no_lives=3, life_loss = 0;
var BUFFER_OBSTACLE_SPACE = 300;
var jump_sound = new Audio("sounds/CanonShoot.wav");
var collision_sound = new Audio("sounds/explosion.wav");
